omni_wheel_front_left_controller:
    type: velocity_controllers/JointVelocityController
    joint: omni_wheel_front_left_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

omni_wheel_front_right_controller:
    type: velocity_controllers/JointVelocityController
    joint: omni_wheel_front_right_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

omni_wheel_back_left_controller:
    type: velocity_controllers/JointVelocityController
    joint: omni_wheel_back_left_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

omni_wheel_back_right_controller:
    type: velocity_controllers/JointVelocityController
    joint: omni_wheel_back_right_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

wheel_controller:
   type: velocity_controllers/JointTrajectoryController
   joints:
      - omni_wheel_front_left_joint
      - omni_wheel_front_right_joint
      - omni_wheel_back_left_joint
      - omni_wheel_back_right_joint
   gains:
     omni_wheel_front_left_joint:  {p: 100,  d: 1, i: 1, i_clamp: 1}
     omni_wheel_front_right_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}
     omni_wheel_back_left_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}
     omni_wheel_back_right_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}